//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyMusicalNote.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyMusicalNote.Resources.Lang.langResources", typeof(langResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string buttonEasy {
            get {
                return ResourceManager.GetString("buttonEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play again.
        /// </summary>
        internal static string buttonGameOverRepeat {
            get {
                return ResourceManager.GetString("buttonGameOverRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string buttonGameOverReturn {
            get {
                return ResourceManager.GetString("buttonGameOverReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string buttonHard {
            get {
                return ResourceManager.GetString("buttonHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear history.
        /// </summary>
        internal static string buttonHistoryClear {
            get {
                return ResourceManager.GetString("buttonHistoryClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to main menu.
        /// </summary>
        internal static string buttonHistoryReturn {
            get {
                return ResourceManager.GetString("buttonHistoryReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string buttonMedium {
            get {
                return ResourceManager.GetString("buttonMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string buttonMenuExit {
            get {
                return ResourceManager.GetString("buttonMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string buttonMenuHistory {
            get {
                return ResourceManager.GetString("buttonMenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        internal static string buttonMenuStart {
            get {
                return ResourceManager.GetString("buttonMenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorect input data. You can play from 5 to 50 notes..
        /// </summary>
        internal static string difficultyAlertContent {
            get {
                return ResourceManager.GetString("difficultyAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string difficultyAlertOk {
            get {
                return ResourceManager.GetString("difficultyAlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number.
        /// </summary>
        internal static string difficultyAlertTitle {
            get {
                return ResourceManager.GetString("difficultyAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear history?.
        /// </summary>
        internal static string historyAlertContent {
            get {
                return ResourceManager.GetString("historyAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string historyAlertNo {
            get {
                return ResourceManager.GetString("historyAlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string historyAlertTitle {
            get {
                return ResourceManager.GetString("historyAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string historyAlertYes {
            get {
                return ResourceManager.GetString("historyAlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the number of notes to practice:.
        /// </summary>
        internal static string labelDifficultyNoteNb {
            get {
                return ResourceManager.GetString("labelDifficultyNoteNb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a difficulty:.
        /// </summary>
        internal static string labelDifficultyTitle {
            get {
                return ResourceManager.GetString("labelDifficultyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy: .
        /// </summary>
        internal static string labelGameOverAccuracy {
            get {
                return ResourceManager.GetString("labelGameOverAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: .
        /// </summary>
        internal static string labelGameOverScore {
            get {
                return ResourceManager.GetString("labelGameOverScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over.
        /// </summary>
        internal static string labelGameOverTitle {
            get {
                return ResourceManager.GetString("labelGameOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string labelHistoryAccuracy {
            get {
                return ResourceManager.GetString("labelHistoryAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string labelHistoryDate {
            get {
                return ResourceManager.GetString("labelHistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string labelHistoryDifficulty {
            get {
                return ResourceManager.GetString("labelHistoryDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string labelHistoryNotes {
            get {
                return ResourceManager.GetString("labelHistoryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string labelHistoryScore {
            get {
                return ResourceManager.GetString("labelHistoryScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string labelHistoryTime {
            get {
                return ResourceManager.GetString("labelHistoryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game results.
        /// </summary>
        internal static string labelHistoryTitle {
            get {
                return ResourceManager.GetString("labelHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string labelLoading {
            get {
                return ResourceManager.GetString("labelLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Musical Note.
        /// </summary>
        internal static string labelMenuTitle {
            get {
                return ResourceManager.GetString("labelMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: .
        /// </summary>
        internal static string labelNote {
            get {
                return ResourceManager.GetString("labelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        internal static string labelNotes {
            get {
                return ResourceManager.GetString("labelNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History is not saved. Error: .
        /// </summary>
        internal static string labelSaveErrorContent {
            get {
                return ResourceManager.GetString("labelSaveErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string labelSaveErrorTitle {
            get {
                return ResourceManager.GetString("labelSaveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        internal static string labelTime {
            get {
                return ResourceManager.GetString("labelTime", resourceCulture);
            }
        }
    }
}
